using System.Collections.Generic;
using Newtonsoft.Json;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SkinPack;
//
//    var manifest = Manifest.FromJson(jsonString);

namespace SkinPack {

    public class Manifest {
        [JsonProperty("format_version")] public long FormatVersion { get; set; }
        [JsonProperty("header")] public Header Header { get; set; }
        [JsonProperty("modules")] public List<Module> Modules { get; set; }

    }

    public class Header {
        [JsonProperty("name")] public string Name { get; set; }
        [JsonProperty("description")] public string Description { get; set; }
        [JsonProperty("uuid")] public string Uuid { get; set; }
        [JsonProperty("version")] public List<long> Version { get; set; }

    }

    public class Module {
        [JsonProperty("type")] public string Type { get; set; }
        [JsonProperty("description")] public string Description { get; set; }
        [JsonProperty("uuid")] public string Uuid { get; set; }
        [JsonProperty("version")] public List<long> Version { get; set; }

    }


}