using Newtonsoft.Json;
using System.Collections.Generic;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using SkinPack;
//
//    var skinsJson = SkinsJson.FromJson(jsonString);
namespace SkinPack {

    public partial class SkinsJson {
        [JsonProperty("geometry")] public string Geometry { get; set; }
        [JsonProperty("skins")] public List<Skin> Skins { get; set; }
        [JsonProperty("serialize_name")] public string SerializeName { get; set; }
        [JsonProperty("localization_name")] public string LocalizationName { get; set; }

    }

    public class Skin {
        [JsonProperty("localization_name")] public string LocalizationName { get; set; }
        [JsonProperty("geometry")] public string Geometry { get; set; }
        [JsonProperty("texture")] public string Texture { get; set; }
        [JsonProperty("type")] public string Type { get; set; }

    }


}